### ISSUE TITLE
[Installer bug] Instalalltion stuck on profile_install

### ISSUE THREAD

**Issue by AndyShade** [dxgldotorg/dxgl#14] opened 2022-11-12 13:47 UTC
![2022-11-12_164118](https://user-images.githubusercontent.com/17062494/201476875-dcd2e6a1-df0a-4824-9fa4-abcbc7aa4178.png)
Running under admin and not
Trying all types of installer current,experimental,legacy and early builds and both archs.
winver 21h2  build 19044.1706

**Comment by dxgldotorg** [comment] 2023-10-15 05:30
Hello.  Anyone having this problem, please open Registry Editor, navigate to HKEY_CURRENT_USER\Software\DXGL, and use File->Export to export the DXGL branch, and attach it here.  That way I can investigate what causes the upgrade process to hang.

**Comment by Ohrwerk** [comment] 2023-10-23 14:02
Test on Windows 7 SP1 Install path C:\Games\DXGL
Clean Install
I have tried it with versions DXGL-0.5.20-win32-msvc10.exe and DXGL-0.5.20-win32.exe, the setup always hangs at DXGLCFG.EXE.
When I kill DXGLCFG.EXE with the taskmanager, the setup continues (same at uninst).
If I then start DXGLCFG.EXE nothing happens, only in the taskmanager the program is displayed.

I could install the older DXGL-0.5.5-win32.exe version, but I can't configure anything.
I get a completely different UI than under Windows XP.
Sorry, but I have no idea how to upload a screenshot here.

Unfortunately there is not much in the registry
 DXGL-0.5.5-win32.exe 
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\DXGL]

[HKEY_CURRENT_USER\Software\DXGL\DXGLTestApp]
"InstallPaths"=hex(7):43,00,3a,00,5c,00,47,00,61,00,6d,00,65,00,73,00,5c,00,44,\
  00,58,00,47,00,4c,00,00,00,00,00

[HKEY_CURRENT_USER\Software\DXGL\Global]
```


DXGL-0.5.20-win32-msvc10.exe
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\DXGL]
"Configuration Version"=dword:00000003

[HKEY_CURRENT_USER\Software\DXGL\Global]

[HKEY_CURRENT_USER\Software\DXGL\Profiles]
```

**Comment by dxgldotorg** [comment] 2023-10-24 05:15
Thanks for the follow-up; I will test to see if either Registry dump causes the freeze.

**Comment by Ohrwerk** [comment] 2023-10-24 10:12
Did you have a debug version?

**Comment by dxgldotorg** [comment] 2023-10-24 15:38
Thanks, seems I may have made a mistake in a patch between 0.5.19 and 0.5.20.  I'll use the attached Registry files to try to make it freeze and when I isolate the effected revision will make a patch.

**Comment by Ohrwerk** [comment] 2023-10-24 15:40
👍

**Comment by dxgldotorg** [comment] 2023-11-10 03:51
Sorry, things have been a bit hectic; I'll try to get to it this weekend, as I get my testing VMs re-deployed.

**Comment by Ohrwerk** [comment] 2023-11-10 07:21
Just don't get stressed.
Christmas is just around the corner and take some time for yourself. Nothing is more important than life.
Have a nice weekend.

**Comment by dxgldotorg** [comment] 2023-11-14 18:04
I've started testing already, haven't reproduced the issue yet but I'll be looking through the loops on profile_install for errors that can result in infinite loops.

**Comment by dxgldotorg** [comment] 2024-01-15 01:48
I believe the changes I have made should mitigate the issue.  Closing #14.

**Comment by dxgldotorg** [comment] 2024-01-17 00:05
New version is now released.  If you find any further issues, please use the "Create memory dump file" option in Task Manager to make a memory dump of dxglcfg.  This version now has debug symbols so I can diagnose issues with this release with a memory dump.

**Comment by Ohrwerk** [comment] 2024-01-17 10:27
I'm sorry to disappoint you, but the setup (dxglconfig) is still stuck.
I have updated the existing working version 0.5.19.
Here is the desired dump, hope it helps.
https://drive.google.com/file/d/1yYzBWmMnRg5hZTX0iGiRlG1_cxvWtAPO/view?usp=sharing

**Comment by dxgldotorg** [comment] 2024-01-17 15:22
Thanks for the memory dump, I have now isolated the issue.  Expect another release soon.

**Comment by dxgldotorg** [comment] 2024-01-17 15:52
Turns out I did something a bit stupid in the dllmain, and that was causing the process to lock up.

Please note the installer does not have debugging symbols, and was not of use to me for diagnosis.

I actually believed it was the registry code, but at least I know that code is now good.

**Comment by dxgldotorg** [comment] 2024-01-17 16:44
Please try the latest release.

**Closed by dxgldotorg** 2024-01-17 16:44 UTC
Labels: bug, regression

**Comment by Ohrwerk** [comment] 2024-01-17 17:52
Yes, thank you very much. The setup is now working.
